### ISSUE TITLE
perform_under is run several times

### ISSUE THREAD

**Issue by yessinf** [piotrmurach/rspec-benchmark#23] opened 2023-05-23 07:40 UTC
I have to do performance test of service for create user, but it's always return raise error because of duplicate record (create method)

I thought sample was default run once. but I don't get it why it run more than 1.

my code 

```ruby
it 'is expected to run under 100ms', :performance_test_1 do
    expect { subject.execute }.to perform_under(5).ms
end
``` 

it runs the code more than 1 so i always failed the performance test because duplicated record

### Describe your environment

* OS version:
* Ruby version: 3.0.3
* RSpec::Benchmark version: 0.6.0

**Comment by piotrmurach** [comment] 2023-06-04 10:52
Hi 👋 

Thanks for using `rspec-benchmark` and submitting this issue report.

This is expected behaviour and by design. Any performance comparison triggers a warmup run of a given expectation to get Ruby going. This helps establish a baseline before the actual performance test runs. In the case of `perform_under` a single iteration is run. Then the actual test measurements are taken. You can influence this with the `warmup` matcher as per the documentation. So in your case, you could do:

```ruby
expect { ... }.to perform_under(5).ms.warmup(0)
```

You could wrap the above with a RSpec matcher like `perform_under_without_warmup`.

As a side note, performance tests are geared towards checking computation that can be run many times without having any side effects. This way you're testing an algorithm and its characteristics. Any setup to make sure that the test has expected data needs to happen before the assertion. Creating a performance test for saving a record to a database has many issues. One of them is what is actually being tested. The web framework performance of saving a record? Database responsiveness? My suggestion would be to focus on testing an algorithm that represents a business logic rather than external services whose performance is not so much under your control.

I hope this helps. I'm going to close this issue as this is not a bug. Please submit a PR if you think the documentation should provide a better explanation of this.

**Closed by piotrmurach** 2023-06-04 10:52 UTC
Labels: bug
